# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Cache-pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-    
    - name: Cache-data
      uses: actions/cache@v2.1.7
      with:
        path: i.txt
        key: ${{ runner.os }}

    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
           pip install -r requirements.txt


    - name: 'Working'
      env:
        ADDRESS: ${{ secrets.ADDRESS }}
        TOKEN: ${{ secrets.TOKEN }}
      run: python main.py
